### ISSUE TITLE
Some QoL updates

### ISSUE THREAD

**Issue by ManikandanUV** [wescode/lemmy_migrate#1]
Hi,

 Thanks for the script, it is very useful. I cloned the repo and made a couple of qol updates to the code on my machine.
   * Automatically parse the url to add https to the input (currently it errors out if https is not supplied)
   * Exclude already subscribed communities from getting resubscribed. This helps reduce runtime and saves processing, and is very useful if you run the script periodically to keep two accounts in sync.

I currently don't have access to create any branches, so I have the changes in my local mahcine. If you provide access to push a separate branch to the repo, I can push the code to it (I currently have them under qol_updates branch on my machine), and can create a pull request for you. You can review the changes and pull them to master if you want.

I haven't worked much on public projects, so let me know if there is a better way to do this.

Thanks!

**Comment by wescode** [comment]
I added you as a collaborator and you can push your branch to qol_updates. As for your secondary enhancement, I actually committed that change a few days ago; it will only subscribe to missing communities on the other accounts.
