### ISSUE TITLE
Lemmy_migrate does not start on Windows 10

### ISSUE THREAD

**Issue by dnet890** [wescode/lemmy_migrate#10]
Hi
I download the Windows build. But, when I run the msi file it just run the cmd file instantly and it's gone. Is it a bug?

**Comment by wescode** [comment]
Just run it from a cmd prompt. You will also need to create the config.ini as described in the docs.

**Comment by dnet890** [comment]
@wescode I tried. But, it does not worked and I checked the exe file it has nothing. What do you think?


https://github.com/wescode/lemmy_migrate/assets/29157187/0e4e1684-9194-4d15-90dd-7a46bc5bb204

**Comment by wescode** [comment]
Don't run "start lemmy-migrate.exe", just lemmy_migrate.exe.
