### ISSUE TITLE
it does not worked on Lemmy 0.19.0-rc.4

### ISSUE THREAD

**Issue by dnet890** [wescode/lemmy_migrate#20]
Hi
my main instance run on 0.19. But, it does not worked. So, I suppose this program does not worked on that latest version. Is that so?
![image](https://github.com/wescode/lemmy_migrate/assets/29157187/40091cce-aa20-4ec5-900e-8ce585869438)

![image](https://github.com/wescode/lemmy_migrate/assets/29157187/e403f7a6-eb9d-4af1-be35-f308c056802d)

**Comment by LiterallyEarth** [comment]
No, you can't start the file like that. First you have to install [Python](https://www.python.org/downloads/windows/) (and on the page download & install one of the Windows installer packages), and then in the Command Prompt type `python lemmy_migrate.py` (then add the arguments you wish, like `-c config.ini)`

**Comment by geezuh** [comment]
`~/src/lemmy_migrate% ./lemmy_migrate.py -c config.ini -u

[ Getting Main Account info - (main) ]
Logged into (main).

[ Getting Account 2 - (act2) ]
 Update main flag set. Updating main account subscriptions

[ Subscribing (main) to new communities from (act2) ]
 Getting list of subscribed communities from the two communities
 0 subscribed communities found in the source (act2)
 0 subscribed communities found in the target (main)`

**Comment by dnet890** [comment]
I have Ubuntu and I want to test it and it is strange that it cannot detect anything of the community I subscribed with (I suspect the main source is version 0.19 is the main problem)

![image](https://github.com/wescode/lemmy_migrate/assets/29157187/f8cd52b7-202f-4b45-a817-1a3ecb415275)
