### ISSUE TITLE
Latest Update does not worked

### ISSUE THREAD

**Issue by dnet890** [wescode/lemmy_migrate#22]
Hi 
I tested it and it does not worked
![image](https://github.com/wescode/lemmy_migrate/assets/29157187/3e934e94-1865-44a9-964c-c4d6bb8be77c)

**Comment by wescode** [comment]
This is actually a misstep on my side, this code requires the requests package and I didn't specify that. You can run: pip install requests.  I will update the reqs so this is obvious.

**Comment by dnet890** [comment]
I did that. But, it still does not worked
![2024-03-09_00-34](https://github.com/wescode/lemmy_migrate/assets/29157187/c05b82bc-57a9-45b3-b994-2a849c38b00f)
![2024-03-09_00-33](https://github.com/wescode/lemmy_migrate/assets/29157187/6dde1b4f-ce9c-485e-b3dc-b5ea78bc9167)
