### ISSUE TITLE
Functionality to update main account from other accounts

### ISSUE THREAD

**Issue by ManikandanUV** [wescode/lemmy_migrate#3]
Hi,

I have added an --update-main argument, and logic to update main account subscriptions from the secondary accounts, for situations where you subscribe to any new communities from one of your secondary accounts and want it to reflect in your main account. I have created a branch update_main on my machine for this code. If you let me push that branch to github, you can take a look and pull it into master if you want.

**Comment by mbentley** [comment]
Why don't you fork the repo and submit a pull request instead of asking for access to pushing a branch?

**Comment by ManikandanUV** [comment]
@mbentley I'm new at collaborating on github. Didn't know I could do that. Thanks for the advice.

**Comment by mbentley** [comment]
Sure thing!  It's much easier to collaborate that way without the need to have push access to the upstream repo.

Typical workflow is:
1. Create a fork
2. Create a feature branch in your fork
3. Commit to your branch in your fork
4. Push the changes to github that you committed in your fork's branch
5. Submit a PR from your new fork's feature branch to this repo's master branch

**Comment by ManikandanUV** [comment]
@mbentley done, thanks for the help
