### ISSUE TITLE
[Feature request] Kbin support

### ISSUE THREAD

**Issue by chris-y** [wescode/lemmy_migrate#7]
Maybe a big ask as there's no published API for Kbin yet, but it would be great to be able to sync/migrate between Lemmy and Kbin.

**Comment by wescode** [comment]
If I get some time I'll look into this. I haven't even looked at the kbin API yet, so I don't know what it currently offers.

**Comment by chris-y** [comment]
The info is here: https://codeberg.org/Kbin/kbin-core/pulls/357
